import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import Onboarding from "@/components/OnBoarding";
import { OnboardingProvider } from '@/components/OnBoardingContext';

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar />
        <OnboardingProvider>
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          {children}
        </main>
              <Onboarding />
          </OnboardingProvider>
        <Toaster />
      </body>
    </html>
  );
}
